# Generated by Django 5.1 on 2024-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the 'blog' app.

    This migration creates the 'Post' model with the following fields:
        - id: Auto-incrementing primary key
        - title: Title of the post (up to 140 characters)
        - body: Main content of the post
        - date: Date and time of publication or creation
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
