# Generated by Django 5.1 on 2024-08-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add the 'signature' field to the 'Post' model.

    This field is a CharField with a maximum length of 140 characters
    and a default value of "You can always change your mind!".
    """

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(
                default='You can always change your mind!',
                max_length=140
            ),
        ),
    ]
